Repository cb-geo/mpm, pull requests merged in 2018-11, with the labels that each got.

#327 :rocket: Locate particles parallelisation
  .circleci/config.yml
  include/mesh.tcc
Labels: Priority: Critical, Status: Completed, Type: Performance

#328 :rocket: Efficient location of point in cell based on the distance from cell centroid
  include/cell.h
  include/cell.tcc
Labels: Priority: Critical, Status: Completed, Type: Performance

#329 :hammer: Fix segfault on location of particles
  include/mesh.tcc
Labels: Priority: Critical, Status: Completed, Type: Core feature

#330 :rocket: :checkered_flag: Resume from cell id
  .circleci/config.yml
  include/hdf5.h
  include/mesh.h
  include/mesh.tcc
  include/mpm.h
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  include/mpm_explicit_usf.tcc
  include/mpm_explicit_usl.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  include/read_mesh.h
  include/read_mesh_ascii.h
  include/read_mesh_ascii.tcc
  tests/mesh_test.cc
  tests/mpm_explicit_usf_test.cc
  tests/mpm_explicit_usf_unitcell_test.cc
  tests/mpm_explicit_usl_test.cc
  tests/mpm_explicit_usl_unitcell_test.cc
  tests/particle_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature

#332 :hammer: Fix fail check io exception handling
  src/io.cc
Labels: Priority: High, Status: Completed, Type: Maintenance

#333 :rocket: Improve performance of traction location using robinmap
  include/map.h
  include/mesh.tcc
  tests/node_map_test.cc
Labels: Priority: High, Status: Completed, Type: Performance

#334 :computer: Refactor assign tractions on particles
  include/mesh.tcc
  include/mpm_explicit.tcc
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#335 :checkered_flg: Assign particle volume
  include/mesh.h
  include/mesh.tcc
  include/mpm_explicit.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  include/read_mesh.h
  include/read_mesh_ascii.h
  include/read_mesh_ascii.tcc
  tests/mesh_test.cc
  tests/particle_test.cc
Labels: Priority: Medium, Status: Completed, Type: Core feature

#336 :computer: Add flag for velocity update
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  include/mpm_explicit_usf.h
  include/mpm_explicit_usf.tcc
  include/mpm_explicit_usl.h
  include/mpm_explicit_usl.tcc
Labels: Priority: Low, Status: Completed, Type: Enhancement

#337 :dart: Coverage ignore errors
  .circleci/config.yml
Labels: Priority: Low, Status: Completed, Type: Maintenance

#339 :computer: Set strain_rate vector as zero using static initialise
  include/cell.tcc
Labels: Priority: Low, Status: Completed, Type: Enhancement

#340 :computer: Use statically defined matrix size for strain-rate
  include/cell.h
  include/cell.tcc
  include/particle.h
  include/particle.tcc
Labels: Priority: Low, Status: Completed, Type: Enhancement

#341 :checkered_flag: Generate points in cell at Gauss points
  CMakeLists.txt
  include/cell.h
  include/cell.tcc
  include/element.h
  include/hexahedron_element.h
  include/hexahedron_element.tcc
  include/hexahedron_quadrature.h
  include/hexahedron_quadrature.tcc
  include/mesh.h
  include/mesh.tcc
  include/mpm_explicit.tcc
  include/quadrature.h
  include/quadrilateral_element.h
  include/quadrilateral_element.tcc
  include/quadrilateral_quadrature.h
  include/quadrilateral_quadrature.tcc
  src/quadrature.cc
  tests/cell_test.cc
  tests/hexahedron_quadrature_test.cc
  tests/mesh_test.cc
  tests/quadrilateral_quadrature_test.cc
  tests/write_mesh_particles_unitcell.cc
Labels: Priority: High, Status: Completed, Type: Core feature

#342 :checkered_flag: Nodal traction
  include/mesh.h
  include/mesh.tcc
  include/mpm.h
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  include/mpm_explicit_usf.h
  include/mpm_explicit_usf.tcc
  include/mpm_explicit_usl.h
  include/mpm_explicit_usl.tcc
  include/node.h
  include/node.tcc
  include/node_base.h
  tests/mesh_test.cc
  tests/node_test.cc
Labels: Priority: Medium, Status: Completed, Type: Core feature

#346 :checkered_flag: Locate points with Newton Raphson fixes #345
  CMakeLists.txt
  include/cell.tcc
  include/mesh.tcc
  tests/point_in_cell_test.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature, Type: Enhancement

#347 :computer: Updated Newton Raphson
  include/cell.tcc
Labels: Priority: High, Status: Completed, Type: Core feature, Type: Enhancement

#349 :checkered_flag: Newton-Raphson with Bilinear Interpolation and Line search fixes #348 fixes #347
  include/cell.tcc
Labels: Priority: Critical, Status: Completed, Type: Enhancement
