Repository cb-geo/mpm, pull requests merged in 2018-09, with the labels that each got.

#245 :checkered_flag: Remove VTK as a required dependency
  CMakeLists.txt
  README.md
  cmake/FindVTK.cmake
  include/mpm.h
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  include/mpm_explicit_usf.tcc
  include/mpm_explicit_usl.tcc
  src/main.cc
Labels: Priority: High, Status: Completed, Type: Core feature, Type: Refactor

#246 :fire: Remove dependency on HDF5 HL
  CMakeLists.txt
Labels: Priority: Low, Status: Completed, Type: Enhancement

#247 :hammer: Revert ":fire: Remove dependency on HDF5 HL"
  CMakeLists.txt
Labels: Priority: High, Status: Completed, Type: Core feature

#249 :checkered_flag: Add traction to particles
  include/cell.h
  include/cell.tcc
  include/hdf5.h
  include/mesh.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/cell_test.cc
  tests/particle_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature

#248 Compute euler angle
  include/geometry.h
  include/geometry.tcc
  tests/geometry_test.cc
Labels: Priority: High, Status: Review needed, Type: Core feature

#252 :art: Refactor throw statements to reduce nesting of for loops in ifs
  include/mesh.tcc
Labels: Priority: Low, Status: Completed, Type: Refactor

#253 :checkered_flag: :hammer: Fixes #251 Constraints tractions are optional
  include/mpm_explicit.tcc
  src/io.cc
Labels: Priority: Low, Status: Completed, Type: Core feature

#242 Assign velocity boundary to cell and compute normal
  include/cell.h
  include/cell.tcc
  include/element.h
  include/hexahedron_element.h
  include/mesh.h
  include/mesh.tcc
  include/quadrilateral_element.h
  tests/hexahedron_element_test.cc
  tests/mesh_test.cc
  tests/quadrilateral_element_test.cc
Labels: Priority: High, Status: Review needed, Type: Core feature

#254 Change function name of inverse rotation matrix
  include/geometry.h
  include/geometry.tcc
  tests/geometry_test.cc
Labels: Priority: Low, Status: Completed, Type: Core feature

#257 :hammer: Fixes #256 remove throw to minimise throwing on all empty cells
  include/cell.h
  include/cell.tcc
Labels: Priority: Low, Status: Completed, Type: Enhancement

#260 :computer: Update particle position based on nodal velocity, and part…
  include/particle.tcc
  tests/particle_test.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature

#261 :checkered_flag: Output strains and velocities as vtp
  include/mesh.h
  include/mesh.tcc
  include/mpm_explicit.tcc
  tests/mesh_test.cc
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#264 :hammer: Fixes #259 add VTK as an optional argument to JSON configura…
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  tests/write_mesh_particles.cc
Labels: Priority: Low, Status: Completed, Type: Viz

#265 :computer: Add compiler option to CMake command
  README.md
Labels: Priority: Low, Status: Completed, Type: Documentation

#266 Fix yield condition from the square of tau to the trace of that
  include/material/bingham.tcc
  tests/material/bingham_test.cc
Labels: Priority: High, Status: Completed, Type: Bug

#267 :rocket: Enable Eigen OpenMP parallelisation
  CMakeLists.txt
Labels: Priority: Medium, Status: Completed, Type: Performance
