Repository cb-geo/mpm, pull requests merged in 2018-08, with the labels that each got.

#182 :art: Stylise doxygen layout
  Doxyfile
  doxygen/addons/bootstrap/jquery.smartmenus.bootstrap.css
  doxygen/addons/bootstrap/jquery.smartmenus.bootstrap.js
  doxygen/addons/bootstrap/jquery.smartmenus.bootstrap.min.js
  doxygen/addons/keyboard/jquery.smartmenus.keyboard.js
  doxygen/addons/keyboard/jquery.smartmenus.keyboard.min.js
  doxygen/customdoxygen.css
  doxygen/doxy-boot.js
  doxygen/footer.html
  doxygen/header.html
  doxygen/jquery.smartmenus.js
  doxygen/jquery.smartmenus.min.js
Labels: Priority: Medium, Status: Completed, Type: Documentation

#183 :computer: Read and assign velocity constraints
  include/mpm_explicit.tcc
  include/node.h
  tests/include/write_mesh_particles.h
  tests/include/write_mesh_particles_unitcell.h
Labels: Priority: Critical, Status: Completed, Type: Core feature

#184 :computer: Pass by const reference of shared_ptr
  include/cell.h
  include/cell.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
Labels: Priority: Critical, Status: Completed, Type: Core feature

#186 :dart: Test clang format on builds
  .circleci/config.yml
  include/cell.tcc
  run-clang-format.py
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#187 :checkered_flag: Clang-tidy modernise override, fixes #172
  CMakeLists.txt
  include/hex_quadrature.h
  include/hex_shapefn.h
  include/material/linear_elastic.h
  include/mpm_explicit.h
  include/node.h
  include/particle.h
  include/quad_quadrature.h
  include/quad_shapefn.h
  include/read_mesh_ascii.h
  run-clang-tidy.py
Labels: Priority: High, Status: In progress, Type: Core feature

#188 :computer: Clang using auto
  include/mpm_explicit.tcc
  include/node.tcc
Labels: Priority: Low

#190 :checkered_flag: Add HDF5 support for particles
  include/mesh.h
  include/mesh.tcc
  include/mpm.h
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  tests/mesh_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature

#191 :computer: Organise clang-tools
  .circleci/config.yml
  clang-tools/run-clang-format.py
  clang-tools/run-clang-tidy.py
Labels: Priority: Low

#192 :fire: Remove assign stress in particle
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/particle_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature

#194 :checkered_flag: Remove elements from a map - fixes #89
  CMakeLists.txt
  include/cell.h
  include/map.h
  include/map.tcc
  include/mesh.h
  include/mesh.tcc
  tests/node_map_test.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature

#195 :pencil: Doxygen docs folder
  Doxyfile
Labels: Priority: Low, Status: Completed, Type: Documentation

#196 :hammer: Include HDF5 in CMake
  CMakeLists.txt
  cmake/FindHDF5.cmake
  cmake/FindPackageHandleStandardArgs.cmake
  cmake/FindPackageMessage.cmake
  cmake/SelectLibraryConfigurations.cmake
Labels: Priority: Critical, Status: Completed, Type: Core feature

#206 :checkered_flag: Fix mpm explicit
  include/material/linear_elastic.tcc
  include/mpm_explicit.tcc
  include/node.h
  include/node.tcc
  include/particle.h
  include/particle.tcc
  tests/node_test.cc
  tests/particle_test.cc
Labels: Priority: Critical, Status: Completed, Type: Bug, Type: Core feature

#209 Calculate jacobian given coordinates and xi
  include/cell.tcc
  include/hex_shapefn.h
  include/hex_shapefn.tcc
  include/particle.h
  include/particle.tcc
  include/quad_shapefn.h
  include/quad_shapefn.tcc
  include/shapefn.h
  tests/hex_shapefn_test.cc
  tests/quad_shapefn_test.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature

#210 :checkered_flag: Calculate Bmatrix with gradients from real cell instead of isoparameteric elements, fixes #199
  include/cell.h
  include/cell.tcc
  include/hex_shapefn.h
  include/hex_shapefn.tcc
  include/particle.tcc
  include/quad_shapefn.h
  include/quad_shapefn.tcc
  include/shapefn.h
  tests/cell_test.cc
  tests/hex_shapefn_test.cc
  tests/particle_test.cc
  tests/quad_shapefn_test.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature

#211 :computer: HDF5 particle strain
  include/hdf5.h
  include/mesh.h
  include/mesh.tcc
Labels: Priority: Medium, Status: Completed, Type: Core feature

#212 :checkered_flag: Update Stress Last
  CMakeLists.txt
  include/logger.h
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  include/mpm_explicit_usl.h
  include/mpm_explicit_usl.tcc
  src/logger.cc
  src/mpm.cc
  tests/include/write_mesh_particles.h
  tests/include/write_mesh_particles_unitcell.h
  tests/mpm_explicit_usl_test.cc
  tests/mpm_explicit_usl_test_unitcell.cc
  tests/write_mesh_particles.cc
  tests/write_mesh_particles_unitcell.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature

#215 :hammer: Refactor particle strain rate fixes #208
  include/particle.tcc
Labels: Priority: Medium, Status: Completed, Type: Core feature

#216 :computer: Write at output steps
  include/mpm.h
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  include/mpm_explicit_usl.h
  include/mpm_explicit_usl.tcc
Labels: Priority: Low, Status: Completed, Type: Core feature

#217 :hammer: Fixes #197 checking gravity dimension
  include/mpm_explicit.tcc
Labels: Priority: Critical, Status: Completed, Type: Bug

#219 :fire: Remove unused particle acceleration and momentum
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/particle_test.cc
Labels: Priority: Low, Status: Completed, Type: Refactor

#220 :computer: :hammer: Refactor MPM Explicit for USF/USL
  CMakeLists.txt
  README.md
  include/logger.h
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  include/mpm_explicit_usf.h
  include/mpm_explicit_usf.tcc
  src/logger.cc
  src/mpm.cc
  tests/mpm_explicit_usf_test.cc
  tests/mpm_explicit_usf_unitcell_test.cc
  tests/mpm_explicit_usl_test.cc
  tests/mpm_explicit_usl_unitcell_test.cc
Labels: Priority: Critical, Status: Completed, Type: Refactor

#221 :checkered_flag: Refactor Shapefn class as Element
  CMakeLists.txt
  include/cell.h
  include/cell.tcc
  include/element.h
  include/hexahedron_element.h
  include/hexahedron_element.tcc
  include/mesh.h
  include/mesh.tcc
  include/mpm_explicit.tcc
  include/particle.tcc
  include/quadrilateral_element.h
  include/quadrilateral_element.tcc
  src/cell.cc
  src/element.cc
  src/shapefn.cc
  tests/cell_container_test.cc
  tests/cell_test.cc
  tests/hexahedron_element_test.cc
  tests/io_test.cc
  tests/material/linear_elastic_test.cc
  tests/mesh_test.cc
  tests/particle_test.cc
  tests/quadrilateral_element_test.cc
  tests/write_mesh_particles.cc
  tests/write_mesh_particles_unitcell.cc
Labels: Priority: High, Status: Completed, Type: Core feature, Type: Refactor

#223 :art: :hammer: Fix eigen vector access with () instead of []
  include/cell.tcc
Labels: Priority: Low, Status: Completed, Type: Refactor

#224 :checkered_flag: Mass matrix
  include/element.h
  include/hexahedron_element.h
  include/hexahedron_element.tcc
  include/quadrilateral_element.h
  include/quadrilateral_element.tcc
  tests/hexahedron_element_test.cc
  tests/quadrilateral_element_test.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature

#166 :computer: Implementation of 3D Bingham model fixes #23
  CMakeLists.txt
  include/cell.h
  include/cell.tcc
  include/material/bingham.h
  include/material/bingham.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  references/Beverly and Tanner (1992) - Numerical analysis of three-dimensional Bingham plastic flow.pdf
  src/material.cc
  tests/cell_test.cc
  tests/material/bingham_test.cc
  tests/particle_test.cc
Labels: Priority: High, Status: Pending, Type: Core feature

#227 :checkered_flag: Add volumetric strain to particle hdf5 for resume support
  include/cell.tcc
  include/hdf5.h
  include/material/bingham.tcc
  include/mesh.tcc
  include/particle.tcc
  tests/particle_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature

#228 :checkered_flag: Add Laplace matrix to element
  include/element.h
  include/hexahedron_element.h
  include/hexahedron_element.tcc
  include/quadrilateral_element.h
  include/quadrilateral_element.tcc
  tests/hexahedron_element_test.cc
  tests/quadrilateral_element_test.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature

#234 :computer: Improve compilation speed using shared library
  .circleci/config.yml
  CMakeLists.txt
  README.md
  include/hexahedron_element.tcc
  include/quadrilateral_element.tcc
Labels: Priority: High, Status: Completed, Type: Enhancement, Type: Performance

#237 :checkered_flag: Add ability to calculate shape functions with deformation gradient fixes #236
  include/element.h
  include/hexahedron_element.h
  include/hexahedron_element.tcc
  include/quadrilateral_element.h
  include/quadrilateral_element.tcc
  tests/hexahedron_element_test.cc
  tests/quadrilateral_element_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature

#235 Compute angle between two vectors
  include/geometry.h
  include/geometry.tcc
  tests/geometry_test.cc
Labels: Priority: High, Status: Revision needed, Type: Core feature

#238 :hammer: Fix geometry documentations
  include/geometry.h
  include/geometry.tcc
Labels: Priority: Low, Status: Completed

#239 :checkered_flag: Update particle position from nodal velocity fixes #203
  include/geometry.h
  include/geometry.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/particle_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature

#240 Fix numbering on 27-node hexahedron
  include/hexahedron_element.h
Labels: Priority: Low, Status: Completed, Type: Enhancement

#230 Add face id in element
  include/element.h
  include/hexahedron_element.h
  include/hexahedron_element.tcc
  include/quadrilateral_element.h
  include/quadrilateral_element.tcc
  tests/hexahedron_element_test.cc
  tests/quadrilateral_element_test.cc
Labels: Priority: High, Status: Revision needed, Type: Core feature

#243 :computer: :hammer: Update nodal volume to use particle shapefns
  include/cell.h
  include/cell.tcc
  tests/cell_test.cc
Labels: Priority: Medium, Status: Completed, Type: Core feature
