Repository cb-geo/mpm, pull requests merged in 2018-10, with the labels that each got.

#229 Create 2D GIMP quadrilateral elements, relates to #179
  CMakeLists.txt
  include/element.h
  include/hexahedron_element.h
  include/quadrilateral_element.h
  include/quadrilateral_gimp_element.h
  include/quadrilateral_gimp_element.tcc
  src/element.cc
  tests/hexahedron_element_test.cc
  tests/quadrilateral_element_test.cc
  tests/quadrilateral_gimp_element_test.cc
Labels: Priority: Critical, Status: In progress, Type: Core feature

#268 :computer: Check if the specified analysis type is valid
  include/factory.h
  src/main.cc
Labels: Priority: High, Status: Completed, Type: Enhancement

#270 :fire: Remove analysis flag from command line
  README.md
  include/io.h
  src/io.cc
  tests/include/write_mesh_particles.h
  tests/include/write_mesh_particles_unitcell.h
  tests/io_test.cc
  tests/mpm_explicit_usf_test.cc
  tests/mpm_explicit_usf_unitcell_test.cc
  tests/mpm_explicit_usl_test.cc
  tests/mpm_explicit_usl_unitcell_test.cc
  tests/write_mesh_particles.cc
  tests/write_mesh_particles_unitcell.cc
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#271 :dart: Test factory class
  CMakeLists.txt
  tests/factory_test.cc
Labels: Priority: Low, Status: Completed, Type: Validation

#272 :computer: Compute particle volume and mass at the start of the step
  include/mpm_explicit_usf.tcc
  include/mpm_explicit_usl.tcc
Labels: Priority: Critical, Status: Completed, Type: Core feature

#273 :computer: Map internal force based on volume
  include/particle.tcc
  tests/particle_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature

#274 :computer: Refactor volume with phases
  include/mesh.tcc
  include/mpm_explicit_usf.tcc
  include/mpm_explicit_usl.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/particle_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature

#275 :checkered_flag: Update volume based on volumetric strain fixes #176
  include/mpm_explicit_usf.tcc
  include/mpm_explicit_usl.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/particle_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature

#279 :computer: Close files upon completion of reading fixes #278
  include/read_mesh_ascii.tcc
Labels: Priority: Critical, Status: Completed, Type: Core feature

#280 :checkered_flag: Assign initial particle stresses
  include/mesh.h
  include/mesh.tcc
  include/mpm_explicit.tcc
  include/particle.h
  include/particle_base.h
  include/read_mesh.h
  include/read_mesh_ascii.h
  include/read_mesh_ascii.tcc
  tests/mesh_test.cc
  tests/particle_test.cc
  tests/read_mesh_ascii_test.cc
  tests/write_mesh_particles_unitcell.cc
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#276 Make shear rate non zero in Bingham
  include/material/bingham.h
  include/material/bingham.tcc
Labels: Priority: Low, Status: Completed, Type: Enhancement

#283 Update FindTBB.cmake
  cmake/FindTBB.cmake
Labels: Priority: Low, Status: Completed, Type: Enhancement

#284 Remove material handle
  include/material/bingham.h
  include/material/bingham.tcc
  include/material/linear_elastic.h
  include/material/linear_elastic.tcc
  include/material/material.h
  include/particle.tcc
  tests/material/bingham_test.cc
  tests/material/linear_elastic_test.cc
Labels: Priority: Medium, Status: Completed, Type: Refactor

#285 :checkered_flag: Default shapefn/grad calls with defromation gradient and particle size, fixes #179
  include/cell.tcc
  include/element.h
  include/hexahedron_element.h
  include/hexahedron_element.tcc
  include/particle.tcc
  include/quadrilateral_element.h
  include/quadrilateral_element.tcc
  include/quadrilateral_gimp_element.h
  include/quadrilateral_gimp_element.tcc
  tests/cell_test.cc
  tests/hexahedron_element_test.cc
  tests/quadrilateral_element_test.cc
Labels: Priority: High, Status: Completed, Type: Refactor

#286 Thermodynamic pressure
  include/hdf5.h
  include/material/bingham.h
  include/material/bingham.tcc
  include/material/linear_elastic.h
  include/material/linear_elastic.tcc
  include/material/material.h
  include/mesh.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/material/bingham_test.cc
  tests/material/linear_elastic_test.cc
  tests/particle_test.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature

#287 Use thermodynamic pressure from material point
  include/material/bingham.tcc
Labels: Priority: High, Status: Completed, Type: Bug

#288 Fix compute volumetric strain
  include/cell.tcc
  tests/material/bingham_test.cc
  tests/particle_test.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature

#290 :hammer: :computer: Fix#289 cell pointer update on particle moving to a new cell
  CMakeLists.txt
  include/cell.h
  include/cell.tcc
  include/mesh.h
  include/mesh.tcc
  include/particle.tcc
  tests/particle_cell_crossing_test.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature

#291 :computer: Require number of particles in the file
  include/read_mesh_ascii.tcc
  tests/read_mesh_ascii_test.cc
  tests/write_mesh_particles.cc
  tests/write_mesh_particles_unitcell.cc
Labels: Priority: Low, Status: Completed, Type: Enhancement

#292 :fire: Remove debug logging of #particles
  include/read_mesh_ascii.tcc
Labels: Priority: Low, Status: Completed, Type: Enhancement

#293 :checkered_flag: Apply traction from particles to node
  include/mpm_explicit.tcc
  include/mpm_explicit_usf.tcc
  include/mpm_explicit_usl.tcc
  include/particle.tcc
  tests/mesh_test.cc
  tests/quadrilateral_gimp_element_test.cc
Labels: Priority: Critical, Status: Completed, Type: Bug

#294 :checkered_flag: Use local sf and Jacobian for computing local cordinates in GIMP
  include/cell.tcc
  include/element.h
  include/hexahedron_element.h
  include/hexahedron_element.tcc
  include/quadrilateral_element.h
  include/quadrilateral_element.tcc
  include/quadrilateral_gimp_element.h
  include/quadrilateral_gimp_element.tcc
  tests/hexahedron_element_test.cc
  tests/quadrilateral_element_test.cc
  tests/quadrilateral_gimp_element_test.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature

#295 :checkered_flag: Fix static analysis
  .circleci/config.yml
  include/cell.tcc
  include/geometry.tcc
  tests/mpm_explicit_usf_test.cc
  tests/mpm_explicit_usl_test.cc
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#296 :art: :hammer: Clang-tidy override
  include/hexahedron_element.h
  include/material/bingham.h
  include/mpm_explicit.h
  include/particle.h
  include/quadrilateral_element.h
Labels: Priority: Low, Status: Completed, Type: Refactor

#297 :checkered_flag: :rocket: MPI distributed MPM code
  .circleci/config.yml
  CMakeLists.txt
  cmake/FindMPI.cmake
  include/io.h
  include/mesh.h
  include/mesh.tcc
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  include/mpm_explicit_usf.tcc
  include/mpm_explicit_usl.tcc
  src/io.cc
  src/main.cc
  tests/mesh_test.cc
  tests/test_main.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature, Type: Performance

#298 :scroll: MPI compilations readme
  README.md
  include/mesh.tcc
Labels: Priority: Low, Status: Completed, Type: Documentation

#299 :checkered_flag: CB-Geo MPM rename in README
  README.md
Labels: Priority: Low, Status: Completed, Type: Documentation

#300 :fire: Refactor vector of mesh & redundant MPI guards clean-up
  README.md
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  include/mpm_explicit_usf.h
  include/mpm_explicit_usf.tcc
  include/mpm_explicit_usl.h
  include/mpm_explicit_usl.tcc
Labels: Priority: Medium, Status: Completed, Type: Core feature

#301 :rocket: :hammer: :fire: Refactor Eigen Matrix to fixed size in node and particles
  include/node.h
  include/node.tcc
  include/node_base.h
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/node_test.cc
  tests/particle_test.cc
Labels: Priority: High, Status: Completed, Type: Refactor

#302 :checkered_flag: Iterate over active nodes fixes #137
  include/mesh.h
  include/mesh.tcc
  include/mpm_explicit_usf.tcc
  include/mpm_explicit_usl.tcc
  tests/mesh_test.cc
Labels: Priority: Medium, Status: Completed, Type: Enhancement, Type: Performance

#303 :rocket: Parallel iterate on MPI Allreduce and nodes with predicate
  include/mesh.tcc
Labels: Priority: Medium, Status: Completed, Type: Performance, Type: Refactor

#306 :checkered_flag: Read particle stresses on MPI
  include/mpm_explicit.tcc
Labels: Priority: Critical, Status: Completed, Type: Core feature

#307 :checkered_flag: Particle global ids
  include/mesh.h
  include/mesh.tcc
  include/mpm_explicit.tcc
  tests/mesh_test.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature

#308 :checkered_flag: :computer: Refactor chunk quantities to a MPI wrapper
  CMakeLists.txt
  include/mpi_wrapper.h
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  tests/mpi_wrapper_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature, Type: Refactor

#309 :computer: Rename MPI files with size/rank at the end
  src/io.cc
Labels: Priority: Low, Status: Completed, Type: Refactor

#310 :checkered_flag: Write Mesh as VTP
  include/cell.h
  include/cell.tcc
  include/mesh.h
  include/mesh.tcc
  include/mpm_explicit.tcc
  include/vtk_writer.h
  src/vtk_writer.cc
  tests/cell_test.cc
  tests/mesh_test.cc
Labels: Priority: Medium, Status: Completed, Type: Core feature

#311 :rocket: :computer: Control # of TBB threads
  README.md
  include/io.h
  include/mesh.h
  include/mesh.tcc
  include/mpm.h
  include/mpm_explicit.tcc
  include/mpm_explicit_usf.tcc
  include/mpm_explicit_usl.tcc
  src/io.cc
  src/main.cc
  tests/io_test.cc
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#312 :computer: Abort MPI when an exception is handled in main
  src/main.cc
Labels: Priority: Critical, Status: Completed, Type: Bug

#313 :checkered_flag: Optional argument to set mesh type as isoparametric/cartesian
  include/cell.h
  include/cell.tcc
  include/mesh.h
  include/mesh.tcc
  include/mpm_explicit.tcc
  include/particle.tcc
  tests/cell_test.cc
  tests/mesh_test.cc
Labels: Priority: High, Status: Completed, Type: Performance

#314 :computer: :rocket: TBB task group to spawn parallel tasks
  include/mpm_explicit.h
  include/mpm_explicit_usf.tcc
  include/mpm_explicit_usl.tcc
Labels: Priority: Low, Status: Completed, Type: Performance

#315 :computer: :rocket: Refactor to define size of interpolate from cell
  include/cell.h
  include/cell.tcc
Labels: Priority: High, Status: Completed, Type: Performance

#316 :computer: Refactor material constructor :fire: Remove material statu…
  include/material/bingham.h
  include/material/bingham.tcc
  include/material/linear_elastic.h
  include/material/linear_elastic.tcc
  include/material/material.h
  include/mpm_explicit.tcc
  include/particle.tcc
  src/material.cc
  tests/material/bingham_test.cc
  tests/material/linear_elastic_test.cc
  tests/particle_cell_crossing_test.cc
  tests/particle_test.cc
Labels: Priority: High, Status: Completed, Type: Refactor

#317 :computer: Newtonian material
  .circleci/config.yml
  CMakeLists.txt
  include/material/newtonian.h
  include/material/newtonian.tcc
  src/material.cc
  tests/material/bingham_test.cc
  tests/material/linear_elastic_test.cc
  tests/material/newtonian_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature

#318 :computer: Reduce tolerance for nodal mass
  include/node.tcc
Labels: Priority: High, Status: Completed, Type: Enhancement

#319 :computer: Additional lock guards on cell operations
  include/cell.tcc
Labels: Priority: High, Status: Completed, Type: Enhancement

#320 :checkered_flag: :hammer: Gimp particle size
  include/hdf5.h
  include/mesh.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/particle_test.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature

#321 :computer: :rocket: Bounding box check for point in cartesian cell
  include/cell.h
  include/cell.tcc
  tests/cell_test.cc
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#322 :hammer: Fix const-correctness in geometry
  include/geometry.h
  include/geometry.tcc
Labels: Priority: Low, Status: Completed, Type: Enhancement

#323 :checkered_flag: Read large files without checking for duplicate item ids in mesh generation
  include/container.h
  include/container.tcc
  include/mesh.h
  include/mesh.tcc
  include/mpm_explicit.tcc
  tests/cell_container_test.cc
  tests/mesh_test.cc
  tests/node_container_test.cc
  tests/particle_container_test.cc
  tests/write_mesh_particles.cc
Labels: Priority: High, Status: Completed, Type: Core feature

#325 Ubuntu dependencies installation guide
  README.md
Labels: Priority: Low, Status: Completed, Type: Documentation
