Repository cb-geo/mpm, pull requests merged in 2019-05, with the labels that each got.

#416 Gimp fix
  include/element.h
  include/hexahedron_element.h
  include/particle.tcc
  include/quadrilateral_element.h
  include/quadrilateral_gimp_element.tcc
  tests/hexahedron_element_test.cc
  tests/quadrilateral_element_test.cc
  tests/quadrilateral_gimp_element_test.cc
Labels: Priority: Critical, Status: Completed, Type: Bug

#415 Add MPM base class fixes #414
  README.md
  include/logger.h
  include/mpm_base.h
  include/mpm_base.tcc
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  src/logger.cc
Labels: Priority: High, Status: Completed, Type: Refactor

#413 Modify the MC model code
  include/material/mohr_coulomb.tcc
Labels: Priority: Critical, Status: Completed, Type: Enhancement, Type: Refactor

#419 :computer: Update CMake prerequisites :art: Clang-format in materials
  CMakeLists.txt
  codecov.yml
  include/material/.clang-format
Labels: Priority: Low, Status: Completed, Type: Enhancement

#418 :computer: Add analytical solution for 2d point cell fixes #399
  CMakeLists.txt
  include/cell.h
  include/cell.tcc
  references/references.md
  tests/cell_test.cc
  tests/point_in_cell_test.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature, Type: Enhancement

#421 :hammer: Remove associated cell, when a particle is removed
  include/mesh.tcc
Labels: Priority: Low, Status: Completed, Type: Enhancement

#422 :hammer: :art: Remove redundant printing
  include/cell.tcc
Labels: Priority: Low, Status: Completed, Type: Performance

#426 Pressure smoothing fixes MPM related to #405
  include/cell.tcc
  include/mpm_explicit.tcc
  include/node.h
  include/node.tcc
  include/node_base.h
  tests/cell_test.cc
  tests/node_test.cc
Labels: Priority: Critical, Status: Completed, Type: Refactor

#425 :computer: Assign material to individual phases fixes #423
  include/mpm_base.tcc
  include/mpm_explicit.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/material/bingham_test.cc
  tests/material/newtonian_test.cc
  tests/particle_cell_crossing_test.cc
  tests/particle_test.cc
Labels: Priority: Medium, Type: Core feature, Type: Refactor

#427 :computer: Reduce redundant computation of point in cell fixes #424
  include/cell.h
  include/cell.tcc
  include/mesh.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/cell_test.cc
  tests/particle_test.cc
  tests/point_in_cell_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature, Type: Performance

#428 :hammer: Fix xi computation in cartesian coordinates
  include/cell.tcc
Labels: Priority: Critical, Status: Completed, Type: Bug

#430 :hammer: Fix #398 nodal mass error on resume
  include/cell.h
  include/mpm_base.tcc
  tests/particle_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature
