Repository cb-geo/mpm, pull requests merged in 2019-02, with the labels that each got.

#357 :checkered_flag: Add state variable to handle history dependence in particles fixes #352
  include/material/bingham.h
  include/material/bingham.tcc
  include/material/linear_elastic.h
  include/material/linear_elastic.tcc
  include/material/material.h
  include/material/newtonian.h
  include/material/newtonian.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/material/bingham_test.cc
  tests/material/linear_elastic_test.cc
  tests/material/newtonian_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature

#361 :art: Merge USL and USF algorithms using analysis_type flag
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  include/mpm_explicit_usf.h
  include/mpm_explicit_usf.tcc
  include/mpm_explicit_usl.h
  include/mpm_explicit_usl.tcc
  src/mpm.cc
  tests/mpm_explicit_usf_test.cc
  tests/mpm_explicit_usf_unitcell_test.cc
  tests/mpm_explicit_usl_test.cc
  tests/mpm_explicit_usl_unitcell_test.cc
Labels: Priority: High, Status: Review needed, Type: Core feature

#365 :computer: :hammer: Add override for state variables
  include/material/bingham.h
  include/material/linear_elastic.h
  include/material/newtonian.h
Labels: Priority: Low, Status: Completed, Type: Enhancement

#367 :computer: Ability to switch to dense hashmap
  codecov.yml
  external/sparsepp/spp.h
  external/sparsepp/spp_config.h
  external/sparsepp/spp_dlalloc.h
  external/sparsepp/spp_memory.h
  external/sparsepp/spp_smartptr.h
  external/sparsepp/spp_stdint.h
  external/sparsepp/spp_timer.h
  external/sparsepp/spp_traits.h
  external/sparsepp/spp_utils.h
  external/sparsepp_license.md
  include/map.h
  include/material/bingham.h
  include/material/bingham.tcc
  include/material/linear_elastic.h
  include/material/linear_elastic.tcc
  include/material/material.h
  include/material/mohr_coulomb.h
  include/material/mohr_coulomb.tcc
  include/material/newtonian.h
  include/material/newtonian.tcc
  include/particle.tcc
  include/particle_base.h
  tests/material/bingham_test.cc
  tests/material/linear_elastic_test.cc
  tests/material/newtonian_test.cc
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#362 Generalize mass matrix
  include/element.h
  include/hexahedron_element.h
  include/hexahedron_element.tcc
  include/quadrilateral_element.h
  include/quadrilateral_element.tcc
  tests/hexahedron_element_test.cc
  tests/quadrilateral_element_test.cc
Labels: Priority: Medium, Status: Completed, Type: Core feature

#368 :computer: Refactor history variable using dense map
  external/sparsepp/spp.h
  external/sparsepp/spp_config.h
  external/sparsepp/spp_dlalloc.h
  external/sparsepp/spp_memory.h
  external/sparsepp/spp_smartptr.h
  external/sparsepp/spp_stdint.h
  external/sparsepp/spp_timer.h
  external/sparsepp/spp_traits.h
  external/sparsepp/spp_utils.h
  external/sparsepp_license.md
  include/map.h
  include/material/bingham.h
  include/material/bingham.tcc
  include/material/linear_elastic.h
  include/material/linear_elastic.tcc
  include/material/material.h
  include/material/newtonian.h
  include/material/newtonian.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/material/bingham_test.cc
  tests/material/linear_elastic_test.cc
  tests/material/newtonian_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature

#372 Friction and velocity constraint order change
  include/node.tcc
Labels: Priority: Critical, Status: Accepted, Type: Bug
