Repository cb-geo/mpm, pull requests merged in 2019-06, with the labels that each got.

#434 :art: Use processor rank before step number in VTK output
  src/io.cc
Labels: Priority: Low, Status: Completed, Type: Validation

#440 Compute cell neighbours and use neighbours for locating particles
  CMakeLists.txt
  include/cell.h
  include/cell.tcc
  include/hexahedron_element.tcc
  include/mesh.h
  include/mesh.tcc
  include/mpm_base.tcc
  tests/cell_test.cc
  tests/hexahedron_element_test.cc
  tests/mesh_cell_neighbours_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature, Type: Enhancement

#439 Assign material and porosity to each phase
  include/cell.h
  include/hexahedron_element.tcc
  include/mpm_base.tcc
  include/mpm_explicit_twophase.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/hexahedron_element_test.cc
  tests/mpm_explicit_twophase_test.cc
  tests/mpm_explicit_twophase_unitcell_test.cc
  tests/particle_test.cc
Labels: Priority: High, Status: Revision needed, Type: Enhancement
