Repository cb-geo/mpm, pull requests merged in 2019-10, with the labels that each got.

#461 :hammer: Use VTK include dirs
  CMakeLists.txt
  README.md
Labels: Priority: Low, Status: Completed, Type: Documentation

#460 Compute local coordinates in cell 2D/3D
  include/cell.tcc
  tests/point_in_cell_test.cc
Labels: Priority: High, Status: In progress, Type: Refactor

#464 :mute: Remove redundant logging in linear elastic :scroll: Add reference
  README.md
  include/material/linear_elastic.tcc
Labels: Priority: Low, Status: Review needed, Type: Maintenance

#467 Refactor cell for analytical solution
  CMakeLists.txt
  clang-tools/format.sh
  include/cell.h
  include/cell.tcc
  include/elements/2d/quadrilateral_element.h
  include/elements/2d/quadrilateral_element.tcc
  include/elements/2d/quadrilateral_gimp_element.h
  include/elements/2d/quadrilateral_gimp_element.tcc
  include/elements/2d/quadrilateral_quadrature.h
  include/elements/2d/quadrilateral_quadrature.tcc
  include/elements/2d/triangle_element.h
  include/elements/2d/triangle_element.tcc
  include/elements/2d/triangle_quadrature.h
  include/elements/2d/triangle_quadrature.tcc
  include/elements/3d/hexahedron_element.h
  include/elements/3d/hexahedron_element.tcc
  include/elements/3d/hexahedron_quadrature.h
  include/elements/3d/hexahedron_quadrature.tcc
  include/elements/element.h
  include/elements/quadrature.h
  tests/cell_test.cc
  tests/elements/hexahedron_element_test.cc
  tests/elements/hexahedron_quadrature_test.cc
  tests/elements/quadrilateral_element_test.cc
  tests/elements/quadrilateral_gimp_element_test.cc
  tests/elements/quadrilateral_quadrature_test.cc
  tests/elements/triangle_element_test.cc
  tests/elements/triangle_quadrature_test.cc
  tests/mesh_test.cc
  tests/point_in_cell_test.cc
Labels: Priority: High, Status: Completed, Type: Refactor

#470 :fire: Remove redundant redefinition of nodal coords fixes #468
  include/cell.h
  include/cell.tcc
  include/elements/2d/quadrilateral_element.h
  include/elements/2d/quadrilateral_element.tcc
  include/elements/2d/triangle_element.h
  include/elements/2d/triangle_element.tcc
  include/elements/3d/hexahedron_element.h
  include/elements/3d/hexahedron_element.tcc
  include/elements/element.h
  tests/cell_test.cc
  tests/mesh_cell_neighbours_test.cc
  tests/mesh_test.cc
Labels: Priority: Low, Status: Completed, Type: Refactor

#476 :computer: :art: Output vector data of particles for viz
  include/mesh.tcc
  include/mpm_base.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/particle_test.cc
Labels: Priority: Low, Status: Completed, Type: Refactor, Type: Viz

#478 CircleCI parallel workflow
  .circleci/config.yml
Labels: Priority: High, Status: Completed, Type: Enhancement

#479 :computer: Fixes #469 refactor NR for 2D/3D in cell
  include/cell.tcc
Labels: Priority: Medium, Status: Completed, Type: Refactor

#481 :hammer: Fixes #480 material property type
  include/cell.tcc
  include/material/material.h
  include/material/material.tcc
  include/particle.tcc
  tests/material/bingham_test.cc
  tests/material/linear_elastic_test.cc
  tests/material/newtonian_test.cc
Labels: Priority: Low, Status: Completed, Type: Enhancement, Type: Refactor

#482 :dart: :hammer: Codecoverage ignore external files
  codecov.yml
Labels: Priority: Low, Status: Completed, Type: Enhancement

#483 Graph partitioning with METIS/ParMETIS
  CMakeLists.txt
  README.md
  cmake/FindMETIS.cmake
  cmake/FindParMETIS.cmake
  include/elements/.clang-format
  include/elements/2d/.clang-format
  include/elements/2d/quadrilateral_element.tcc
  include/elements/3d/.clang-format
  include/graph.h
  include/graph.tcc
  include/mesh.h
  include/mesh.tcc
  include/mpm_base.h
  include/mpm_base.tcc
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  tests/graph_test.cc
Labels: Priority: Critical, Status: In progress, Type: Core feature, Type: Performance

#485 :pencil: METIS and ParMETIS installation instructions
  README.md
Labels: Priority: Low, Status: Completed

#487 Fix minor errors in cmake after metis
  CMakeLists.txt
Labels: Priority: Low, Status: Completed, Type: Maintenance
