Repository cb-geo/mpm, pull requests merged in 2019-03, with the labels that each got.

#377 Fix 2D rotation matrix
  include/geometry.tcc
  tests/geometry_test.cc
Labels: Priority: Low, Status: Completed, Type: Bug

#378 Add rotation matrix to node
  include/mesh.h
  include/mesh.tcc
  include/node.h
  include/node.tcc
  include/node_base.h
  tests/mesh_test.cc
Labels: Priority: High, Status: Review needed, Type: Core feature

#380 :art: Restructure geometry class
  CMakeLists.txt
  include/geometry.h
  include/geometry.tcc
  src/geometry.cc
  tests/geometry_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature

#382 Add rotation matrix to node - refer to #378
  CMakeLists.txt
  include/geometry.h
  include/geometry.tcc
  include/mesh.h
  include/mesh.tcc
  src/geometry.cc
  tests/geometry_test.cc
  tests/mesh_test.cc
Labels: Priority: Medium, Status: Completed, Type: Core feature

#379 Friction
  include/mesh.h
  include/mesh.tcc
  include/mpm_explicit.tcc
  include/node.h
  include/node.tcc
  include/node_base.h
  include/read_mesh.h
  include/read_mesh_ascii.h
  include/read_mesh_ascii.tcc
  tests/node_test.cc
Labels: Priority: Low, Status: Accepted, Status: Completed, Type: Core feature

#385 Applying inclined velocity boundary constraint at node
  include/node.h
  include/node.tcc
  tests/node_test.cc
Labels: Priority: High, Status: In progress, Type: Core feature

#391 :computer: Explicitly use nodal velocity to update coordinates on velocity update
  include/particle.tcc
Labels: Priority: Medium, Status: Review needed, Type: Bug

#394 :wrench: fixes #392 bmatrix calculation
  .gitignore
  include/hexahedron_element.tcc
  include/quadrilateral_element.tcc
  include/quadrilateral_gimp_element.tcc
  tests/material/bingham_test.cc
  tests/material/newtonian_test.cc
Labels: Priority: Critical, Status: In progress, Type: Bug
