Repository cb-geo/mpm, pull requests merged in 2019-04, with the labels that each got.

#396 :computer: :dart: Pressure smoothing with MPI
  include/cell.h
  include/cell.tcc
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  include/node.h
  include/node.tcc
  include/node_base.h
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/cell_test.cc
  tests/node_test.cc
  tests/particle_test.cc
Labels: Priority: Medium, Status: Completed, Type: Core feature

#397 Assign materials to particles sets
  include/container.h
  include/io.h
  include/mesh.h
  include/mesh.tcc
  include/mpm.h
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  src/io.cc
  tests/io_test.cc
  tests/write_mesh_particles.cc
  tests/write_mesh_particles_unitcell.cc
Labels: Priority: High, Status: In progress, Type: Core feature

#401 Particle and node sets
  include/container.h
  include/io.h
  include/mesh.h
  include/mesh.tcc
  include/mpm.h
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  src/io.cc
  tests/io_test.cc
  tests/write_mesh_particles.cc
  tests/write_mesh_particles_unitcell.cc
Labels: Priority: High, Status: Completed, Type: Core feature

#406 :hammer: Issue do not update volume without changing density
  include/mpm_explicit.tcc
Labels: Priority: Critical, Status: Completed, Type: Bug

#408 General velocity and friction boundary fixes #20
  include/mesh.h
  include/mesh.tcc
  include/mpm_explicit.tcc
  include/node.h
  include/node.tcc
  include/node_base.h
  include/read_mesh.h
  include/read_mesh_ascii.h
  include/read_mesh_ascii.tcc
  tests/mesh_test.cc
  tests/node_test.cc
  tests/read_mesh_ascii_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature

#409 Volume update
  include/mpm_explicit.tcc
  include/particle.h
  include/particle.tcc
Labels: Priority: Critical, Status: Completed, Type: Core feature
