Repository cb-geo/mpm, pull requests merged in 2019-12, with the labels that each got.

#507 :computer: State variables and Material ID in HDF5
  CMakeLists.txt
  include/hdf5_particle.h
  include/mesh.h
  include/mesh.tcc
  include/mpi_datatypes.h
  include/mpm_base.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  src/hdf5_particle.cc
  tests/mpi_particle_test.cc
  tests/particle_test.cc
Labels: Priority: Critical, Status: Completed, Status: Review needed, Type: Core feature, Type: Enhancement

#509 Feature surrounding cell neighbour
  include/cell.h
  include/mesh.tcc
  tests/mesh_cell_neighbours_test.cc
Labels: Priority: Medium, Status: In progress, Type: Core feature

#513 :computer: MPI transfer of particles in non-local rank
  .circleci/config.yml
  CMakeLists.txt
  include/mesh.h
  include/mesh.tcc
  include/mpi_datatypes.h
  include/mpi_wrapper.h
  include/mpm_base.h
  include/mpm_explicit.tcc
  tests/mesh_test.cc
  tests/mpi_transfer_particle_test.cc
  tests/mpi_wrapper_test.cc
Labels: Priority: Critical, Status: Completed, Type: Performance

#517 Fixes #515 Send/recv vector of particles
  include/mesh.tcc
Labels: Priority: High, Status: Completed, Type: Performance

#518 #516 Use shared nodes to perform MPI gather
  include/cell.h
  include/cell.tcc
  include/mesh.h
  include/mesh.tcc
  include/mpm_explicit.tcc
  include/node.h
  include/node.tcc
  include/node_base.h
  tests/cell_test.cc
  tests/mesh_test.cc
  tests/mpi_transfer_particle_test.cc
  tests/node_test.cc
Labels: Priority: Critical, Status: Completed, Type: Performance

#519 :art: Write a parallel vtp file that fetches all vector attributes
  CMakeLists.txt
  include/io.h
  include/mpm_base.tcc
  include/vtk_writer.h
  src/io.cc
  src/vtk_writer.cc
  tests/vtk_writer_test.cc
Labels: Priority: Low, Status: Completed, Type: Enhancement

#510 :computer: Identify interface nodes with multiple material contact
  include/cell.h
  include/cell.tcc
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  include/node.h
  include/node.tcc
  include/node_base.h
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/cell_test.cc
  tests/node_test.cc
  tests/particle_test.cc
Labels: Priority: Medium, Status: Review needed, Type: Core feature

#520 :rocket: Domain decomposition in MPM
  .circleci/config.yml
  include/mesh.h
  include/mesh.tcc
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  include/node.h
  include/node_base.h
  tests/mesh_test.cc
  tests/mpi_transfer_particle_test.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature, Type: Performance

#521 :hammer: Fix any source problem with domain decomposition
  include/mesh.tcc
Labels: Priority: Critical, Status: Completed, Type: Maintenance

#522 :hammer: Fix deadlock in MPI comms with domain decomposition
  .circleci/config.yml
  include/mesh.h
  include/mesh.tcc
  include/mpm_explicit.tcc
  tests/mpi_transfer_particle_test.cc
Labels: Priority: Critical, Status: Completed, Type: Bug, Type: Maintenance, Type: Performance

#523 TBB parallel_for
  include/container.h
  include/mesh.h
  include/mesh.tcc
Labels: Priority: High, Status: Completed, Type: Performance

#524 :computer: Fixes #512 Generate material points and add to mesh directly
  include/mesh.h
  include/mesh.tcc
  include/mpm_base.tcc
  tests/mesh_test.cc
  tests/mpm_explicit_usf_test.cc
  tests/mpm_explicit_usf_unitcell_test.cc
  tests/mpm_explicit_usl_test.cc
  tests/mpm_explicit_usl_unitcell_test.cc
Labels: Priority: Medium, Status: Completed, Type: Core feature, Type: Enhancement

#525 :computer: Graph partitioning with KaHIP
  .circleci/config.yml
  CMakeLists.txt
  README.md
  cmake/FindKaHIP.cmake
  cmake/FindMETIS.cmake
  cmake/FindParMETIS.cmake
  include/graph.h
  include/graph.tcc
  include/mesh.h
  include/mesh.tcc
  include/mpm_base.h
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  tests/graph_test.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature, Type: Performance

#526 Refactor/mpm explicit
  include/mpm_explicit.h
  include/mpm_explicit.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/particle_cell_crossing_test.cc
  tests/particle_test.cc
Labels: Priority: Medium, Status: Completed, Type: Refactor

#527 :rocket: Refactor compute strain rate
  CMakeLists.txt
  README.md
  include/cell.h
  include/cell.tcc
  include/elements/2d/quadrilateral_element.h
  include/elements/2d/quadrilateral_element.tcc
  include/elements/2d/triangle_element.h
  include/elements/2d/triangle_element.tcc
  include/elements/3d/hexahedron_element.h
  include/elements/3d/hexahedron_element.tcc
  include/elements/element.h
  include/particle.h
  include/particle.tcc
  tests/cell_test.cc
  tests/elements/hexahedron_element_test.cc
  tests/elements/hexahedron_gimp_element_test.cc
  tests/elements/quadrilateral_element_test.cc
  tests/elements/quadrilateral_gimp_element_test.cc
  tests/elements/triangle_element_test.cc
Labels: Priority: High, Status: In progress, Type: Performance, Type: Refactor

#511 Traction force
  CMakeLists.txt
  external/json.hpp
  external/json_license.md
  include/functions/function_base.h
  include/functions/linear_function.h
  include/io.h
  include/loads/particle_traction.h
  include/mesh.h
  include/mesh.tcc
  include/mpm.h
  include/mpm_base.h
  include/mpm_base.tcc
  include/node.h
  include/node.tcc
  include/node_base.h
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  include/read_mesh.h
  include/read_mesh_ascii.h
  include/read_mesh_ascii.tcc
  include/solvers/mpm_explicit.h
  include/solvers/mpm_explicit.tcc
  src/functions/functions.cc
  src/functions/linear_function.cc
  src/io.cc
  tests/functions_test.cc
  tests/mesh_test.cc
  tests/mpm_explicit_usf_test.cc
  tests/mpm_explicit_usf_unitcell_test.cc
  tests/mpm_explicit_usl_test.cc
  tests/mpm_explicit_usl_unitcell_test.cc
  tests/node_test.cc
  tests/particle_test.cc
  tests/particle_traction_test.cc
  tests/read_mesh_ascii_test.cc
  tests/write_mesh_particles.cc
  tests/write_mesh_particles_unitcell.cc
Labels: Priority: Medium, Status: Completed, Status: Review needed, Type: Core feature

#528 Particle/generator with files and gauss points fixes #437 fixes #438
  CMakeLists.txt
  include/io/io.h
  include/io/io_mesh.h
  include/io/io_mesh_ascii.h
  include/io/io_mesh_ascii.tcc
  include/io/logger.h
  include/io/vtk_writer.h
  include/levelset.h
  include/levelset.tcc
  include/mesh.h
  include/mesh.tcc
  include/mpm.h
  include/mpm_base.h
  include/mpm_base.tcc
  include/polynomial.h
  include/polynomial.tcc
  include/solvers/mpm_explicit.h
  include/solvers/mpm_explicit.tcc
  src/io/io.cc
  src/io/io_mesh.cc
  src/io/logger.cc
  src/io/vtk_writer.cc
  src/main.cc
  src/mpm.cc
  src/read_mesh.cc
  tests/io/io_mesh_ascii_test.cc
  tests/io/io_test.cc
  tests/io/vtk_writer_test.cc
  tests/io/write_mesh_particles.cc
  tests/io/write_mesh_particles_unitcell.cc
  tests/mesh_test.cc
  tests/mpm_explicit_usf_test.cc
  tests/mpm_explicit_usf_unitcell_test.cc
  tests/mpm_explicit_usl_test.cc
  tests/mpm_explicit_usl_unitcell_test.cc
Labels: Priority: Medium, Status: In progress, Type: Core feature

#530 :hammer: Fix JSON exception handling in MPM base
  include/mpm_base.tcc
Labels: Priority: Critical, Status: Completed, Type: Bug

#531 Static load
  include/loads/particle_traction.h
  include/mpm_base.tcc
Labels: Priority: High, Status: Completed, Type: Bug

#532 Nodal and particle boundary conditions fixes #529
  CMakeLists.txt
  include/io/io_mesh.h
  include/io/io_mesh_ascii.h
  include/io/io_mesh_ascii.tcc
  include/loads_bcs/friction_constraint.h
  include/loads_bcs/traction.h
  include/loads_bcs/velocity_constraint.h
  include/mesh.h
  include/mesh.tcc
  include/mpm_base.h
  include/mpm_base.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  include/solvers/mpm_explicit.tcc
  tests/io/io_mesh_ascii_test.cc
  tests/io/io_test.cc
  tests/mesh_test.cc
  tests/particle_test.cc
  tests/particle_traction_test.cc
Labels: Priority: Medium, Status: Completed, Type: Refactor

#534 :hammer: Refactor update volume, reduce compute volume computation
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  include/solvers/mpm_explicit.tcc
  tests/particle_test.cc
Labels: Priority: Low, Status: Completed, Type: Core feature

#535 Refactor pressure computation to material
  include/material/bingham.h
  include/material/bingham.tcc
  include/material/linear_elastic.h
  include/material/linear_elastic.tcc
  include/material/material.h
  include/material/newtonian.h
  include/material/newtonian.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/material/bingham_test.cc
  tests/material/linear_elastic_test.cc
  tests/material/newtonian_test.cc
  tests/particle_test.cc
Labels: Priority: High, Status: Completed, Type: Enhancement, Type: Refactor
