Repository cb-geo/mpm, pull requests merged in 2019-11, with the labels that each got.

#488 Write displacement on .h5 files
  include/hdf5.h
  include/mesh.tcc
  include/particle.tcc
  tests/particle_test.cc
Labels: Priority: High, Status: Review needed, Type: Core feature, Type: Feature request

#489 :hammer: Fix static analysis errors
  .circleci/config.yml
  README.md
  clang-tools/.clang-tidy
  clang-tools/run-clang-tidy.py
  cmake/FindBoost.cmake
  include/graph.h
  src/main.cc
  tests/test_main.cc
Labels: Priority: Low, Status: Completed, Type: Maintenance

#490 :hammer: Fix assigning material properties to set
  include/particle.tcc
Labels: Priority: Critical, Status: Completed, Type: Bug

#491 :computer: Static analysis check of unsigned checks
  include/cell.tcc
  include/node.tcc
  include/particle.tcc
Labels: Priority: Low, Status: Completed, Type: Maintenance

#492 Change iterating through particles to iterating through cells
  include/cell.h
  include/mesh.h
  include/mesh.tcc
  include/mpm_explicit.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
Labels: Priority: High, Status: In progress, Type: Performance

#493 Parallel/graph
  include/cell.h
  include/cell.tcc
  include/graph.h
  include/graph.tcc
  include/mesh.h
  include/mesh.tcc
  include/mpm_explicit.tcc
  tests/cell_test.cc
  tests/mesh_test.cc
Labels: Priority: Medium, Status: Completed, Type: Performance, Type: Refactor

#495 [HDF5] Modify write particles hdf5
  README.md
  include/mesh.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/particle_test.cc
Labels: Priority: Medium, Status: In progress, Type: Refactor

#496 :bug: Fixed face neighbour compute function
  include/mesh.tcc
Labels: Priority: Critical, Status: Completed, Type: Bug

#498 :hammer: Fix ParMETIS by removing incomplete test
  cmake/FindParMETIS.cmake
Labels: Priority: Critical, Status: Completed, Type: Maintenance

#500 :computer: :rocket: Fast builds in CI using ninja
  .circleci/config.yml
  README.md
Labels: Priority: Low, Status: Completed, Type: Performance

#501 :pencil: Add compilation with MPI/ParMETIS
  README.md
Labels: Priority: Low, Status: Completed, Type: Documentation

#503 :computer: Refactor and remove phases in particle class
  include/material/bingham.tcc
  include/material/newtonian.tcc
  include/mesh.tcc
  include/mpm_base.h
  include/mpm_base.tcc
  include/mpm_explicit.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  src/mpm.cc
  src/particle.cc
  tests/include/write_mesh_particles.h
  tests/include/write_mesh_particles_unitcell.h
  tests/material/bingham_test.cc
  tests/material/linear_elastic_test.cc
  tests/material/newtonian_test.cc
  tests/mesh_cell_neighbours_test.cc
  tests/mesh_test.cc
  tests/mpm_explicit_usf_test.cc
  tests/mpm_explicit_usf_unitcell_test.cc
  tests/mpm_explicit_usl_test.cc
  tests/mpm_explicit_usl_unitcell_test.cc
  tests/particle_cell_crossing_test.cc
  tests/particle_container_test.cc
  tests/particle_test.cc
  tests/write_mesh_particles.cc
  tests/write_mesh_particles_unitcell.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature, Type: Refactor

#447 Added 3D gimp functionality
  CMakeLists.txt
  include/elements/3d/hexahedron_gimp_element.h
  include/elements/3d/hexahedron_gimp_element.tcc
  src/element.cc
  tests/elements/hexahedron_gimp_element_test.cc
Labels: Priority: High, Status: Review needed, Type: Core feature

#505 :rocket: MPI particle send/receive
  .circleci/config.yml
  CMakeLists.txt
  include/cell.h
  include/container.h
  include/data_types.h
  include/hdf5_particle.h
  include/io.h
  include/map.h
  include/mesh.h
  include/mpi_datatypes.h
  include/node.h
  include/node_base.h
  include/particle.h
  include/particle_base.h
  include/read_mesh.h
  include/read_mesh_ascii.h
  include/vtk_writer.h
  tests/mpi_particle_test.cc
  tests/particle_cell_crossing_test.cc
  tests/particle_test.cc
Labels: Priority: Medium, Status: Review needed, Type: Performance

#506 :computer: CMake/build
  .circleci/config.yml
  CMakeLists.txt
  README.md
Labels: Priority: Medium, Status: Completed, Type: Core feature
