Repository cb-geo/mpm, pull requests merged in 2020-07, with the labels that each got.

#657 [Hotfix] Particle on edge error
  include/cell.tcc
  tests/cell_test.cc
Labels: Priority: Critical, Type: Bug

#660 Fix hardening in NorSand
  include/materials/norsand.tcc
  tests/materials/norsand_test.cc
Labels: Priority: Critical, Type: Bug

#655 Feature/contact/normal vector
  include/mesh.tcc
  include/node.h
  include/node.tcc
  include/node_base.h
  include/particles/particle.h
  include/particles/particle.tcc
  include/particles/particle_base.h
  include/solvers/mpm_explicit.tcc
  tests/interface_test.cc
Labels: Priority: Low, Status: Review needed, Type: Core feature

#659 [Hotfix] Removed unused variables
  include/elements/2d/triangle_quadrature.tcc
  include/materials/modified_cam_clay.tcc
  include/materials/mohr_coulomb.tcc
  include/mesh.tcc
  include/mpi_datatypes.h
  include/node.tcc
  include/solvers/mpm_base.tcc
  tests/io/write_mesh_particles.cc
  tests/io/write_mesh_particles_unitcell.cc
Labels: Priority: Medium, Type: Maintenance

#663 Variable cleanup
  include/graph.h
  include/graph.tcc
  include/solvers/mpm_base.tcc
  tests/mpi_transfer_particle_test.cc
  tests/node_test.cc
Labels: Priority: Low, Type: Maintenance

#661 Feature/parallel/openmp
  CMakeLists.txt
  README.md
  cmake/FindTBB.cmake
  include/containers/vector.h
  include/containers/vector.tcc
  include/io/io.h
  include/loads_bcs/constraints.h
  include/loads_bcs/constraints.tcc
  include/mesh.h
  include/mesh.tcc
  include/particles/particle.h
  include/particles/particle.tcc
  include/solvers/mpm_base.h
  include/solvers/mpm_explicit.tcc
  src/io/io.cc
  src/main.cc
Labels: Priority: Medium, Status: Completed, Type: Performance, Type: Refactor

#664 Remove MPM_BUILD_LIB option
  .circleci/config.yml
  CMakeLists.txt
Labels: Priority: Medium, Status: Review needed, Type: Maintenance

#669 Hotfix/circleci nightly
  .circleci/config.yml
Labels: Priority: Critical, Status: Review needed, Type: Core feature, Type: Validation

#668 :construction: OpenMP compilation with set
  README.md
Labels: Priority: Critical, Status: Help wanted, Status: In progress, Type: Bug

#666 Remove fedora command in partio installation commands
  README.md
Labels: Priority: Low, Type: Documentation

#670 :fire: :art: Refactor nested namespace - to avoid needing c++17
  include/hdf5_particle.h
  src/hdf5_particle.cc
Labels: Priority: High, Status: Review needed, Type: Maintenance

#667 Add return value for nodal friction and velocity constraints
  include/solvers/mpm_base.tcc
Labels: Priority: Low, Status: In progress, Type: Core feature

#665 :hammer: Assign material during initialize particle fix key not found fixes #651
  include/particles/particle.tcc
Labels: Priority: Critical, Status: Review needed, Type: Bug

#672 Use flat_map to handle particle properties
  external/flat/LICENSE_1_0.txt
  external/flat/README.md
  external/flat/flat_map.hpp
  external/flat/flat_multimap.hpp
  external/flat/flat_multiset.hpp
  external/flat/flat_set.hpp
  external/flat/impl/class_def.hpp
  external/flat/impl/container_traits.hpp
  external/flat/impl/flat_impl.hpp
  include/node.h
  include/node_base.h
  include/particles/particle_base.h
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#676 Improve lock performance with SpinMutex and OpenMP static scheduling
  README.md
  include/mesh.tcc
  include/mutex.h
  include/node.h
  include/node.tcc
  include/solvers/mpm_base.tcc
Labels: Priority: Medium, Status: Completed, Type: Performance

#674 Feature/material_id
  include/solvers/mpm_base.tcc
  tests/include/write_mesh_particles.h
  tests/io/write_mesh_particles.cc
  tests/mpm_explicit_usf_test.cc
  tests/mpm_explicit_usl_test.cc
Labels: Priority: Medium, Status: Review needed, Type: Feature request

#677 Performance/openmp schedule mutex
  README.md
  include/mesh.tcc
  include/mutex.h
  include/node.h
  include/node.tcc
Labels: Priority: Medium, Status: Completed, Type: Enhancement, Type: Performance

#675 Feature/multiphase material
  include/generators/injection.h
  include/mesh.h
  include/mesh.tcc
  include/particles/particle.h
  include/particles/particle.tcc
  include/particles/particle_base.h
  include/solvers/mpm_base.h
  include/solvers/mpm_base.tcc
  include/solvers/mpm_explicit.h
  include/solvers/mpm_explicit.tcc
  tests/io/write_mesh_particles.cc
  tests/io/write_mesh_particles_unitcell.cc
  tests/mesh_test_2d.cc
  tests/mesh_test_3d.cc
  tests/mpm_explicit_usf_test.cc
  tests/particle_cell_crossing_test.cc
Labels: Priority: High, Status: Review needed, Type: Enhancement

#678 [Hotfix] Assign material state variables
  include/particles/particle.tcc
Labels: Type: Bug, Type:FastPR
