Repository cb-geo/mpm, pull requests merged in 2020-03, with the labels that each got.

#576 [Cleanup] Particles and solvers folder
  CMakeLists.txt
  include/particles/particle.h
  include/particles/particle.tcc
  include/particles/particle_base.h
  include/particles/particle_base.tcc
  include/solvers/mpm.h
  include/solvers/mpm_base.h
  include/solvers/mpm_base.tcc
Labels: Priority: Low, Type: Maintenance

#569 Neighbour Particles
  CMakeLists.txt
  include/mesh.h
  include/mesh.tcc
  include/particles/particle.h
  include/particles/particle.tcc
  include/particles/particle_base.h
  include/solvers/mpm_base.tcc
  tests/graph_test.cc
  tests/mesh_neighbours_test.cc
  tests/mpi_transfer_particle_test.cc
Labels: Priority: Medium, Status: In progress, Type: Enhancement

#562 [Constitutive] Modified Cam-Clay
  CMakeLists.txt
  include/material/modified_cam_clay.h
  include/material/modified_cam_clay.tcc
  src/material.cc
  tests/material/modified_cam_clay_test.cc
Labels: Priority: High, Status: Review needed, Type: Core feature

#577 :art: Restructure container files and materials
  CMakeLists.txt
  include/containers/map.h
  include/containers/map.tcc
  include/containers/vector.h
  include/containers/vector.tcc
  include/graph.h
  include/graph.tcc
  include/materials/bingham.h
  include/materials/bingham.tcc
  include/materials/linear_elastic.h
  include/materials/linear_elastic.tcc
  include/materials/material.h
  include/materials/material.tcc
  include/materials/modified_cam_clay.h
  include/materials/modified_cam_clay.tcc
  include/materials/mohr_coulomb.h
  include/materials/mohr_coulomb.tcc
  include/materials/newtonian.h
  include/materials/newtonian.tcc
  include/materials/norsand.h
  include/materials/norsand.tcc
  include/mesh.h
  include/mesh.tcc
  include/particles/particle_base.h
  include/solvers/mpm_base.h
  src/material.cc
  tests/cell_vector_test.cc
  tests/graph_test.cc
  tests/materials/bingham_test.cc
  tests/materials/linear_elastic_test.cc
  tests/materials/modified_cam_clay_test.cc
  tests/materials/mohr_coulomb_test.cc
  tests/materials/newtonian_test.cc
  tests/materials/norsand_test.cc
  tests/mpi_particle_test.cc
  tests/mpi_transfer_particle_test.cc
  tests/node_vector_test.cc
  tests/particle_cell_crossing_test.cc
  tests/particle_vector_test.cc
Labels: Priority: Low, Status: Completed, Type: Maintenance

#580 :computer: Particles set id when generating particles - fixes #578
  include/mesh.h
  include/mesh.tcc
  tests/io/write_mesh_particles.cc
  tests/io/write_mesh_particles_unitcell.cc
  tests/mesh_test.cc
Labels: Priority: Medium, Status: Review needed, Type: Enhancement

#574 Property pool struct
  CMakeLists.txt
  include/nodal_properties.h
  src/nodal_properties.cc
  tests/nodal_properties_test.cc
Labels: Priority: High, Status: In progress, Type: Core feature

#581 :computer: Continue running simulation when locate particles fn fails flag
  include/solvers/mpm_base.h
  include/solvers/mpm_base.tcc
  include/solvers/mpm_explicit.h
  include/solvers/mpm_explicit.tcc
  tests/io/write_mesh_particles.cc
  tests/io/write_mesh_particles_unitcell.cc
Labels: Priority: Medium, Status: Review needed, Type: Core feature

#583 :computer: Write VTK stresses and strains as tensors
  include/io/vtk_writer.h
  include/mesh.h
  include/mesh.tcc
  include/particles/particle.h
  include/particles/particle.tcc
  include/particles/particle_base.h
  include/solvers/mpm_base.h
  include/solvers/mpm_base.tcc
  include/solvers/mpm_explicit.h
  src/io/vtk_writer.cc
  tests/io/vtk_writer_test.cc
  tests/mesh_test.cc
  tests/particle_test.cc
Labels: Priority: Medium, Status: Review needed, Type: IO, Type: Viz

#586 [Constitutive Law] Incompressible Bingham
  include/materials/bingham.h
  include/materials/bingham.tcc
  tests/materials/bingham_test.cc
Labels: Priority: Low

#585 [Constitutive Law] Minor Mohr-Coulomb
  include/materials/mohr_coulomb.tcc
Labels: Priority: Low
