Repository cb-geo/mpm, pull requests merged in 2020-08, with the labels that each got.

#683 [Feature] State variable vtk output for different phases
  include/mesh.h
  include/mesh.tcc
  include/solvers/mpm_base.h
  include/solvers/mpm_base.tcc
  tests/io/write_mesh_particles.cc
  tests/io/write_mesh_particles_unitcell.cc
Labels: Priority: Medium, Status: Review needed, Type: Enhancement, Type: IO

#687 :hammer: vtk statevars is set as an optional argument
  include/solvers/mpm_base.tcc
Labels: Priority: Low, Status: Completed, Type: Maintenance

#684 [Feature] VTK output vars
  include/mesh.h
  include/mesh.tcc
  include/particles/particle.h
  include/particles/particle.tcc
  include/particles/particle_base.h
  include/solvers/mpm_base.h
  include/solvers/mpm_base.tcc
  tests/io/write_mesh_particles.cc
  tests/io/write_mesh_particles_unitcell.cc
  tests/mesh_test_2d.cc
  tests/mesh_test_3d.cc
  tests/particle_test.cc
Labels: Priority: High, Status: Review needed, Type: Feature request, Type: IO

#690 :pencil: add name to author list
  AUTHORS.md
Labels: Priority: Low, Status: Review needed, Type: Documentation

#685 Refactor/mpm solvers to handle different stress update schemes
  CMakeLists.txt
  include/contacts/contact.h
  include/contacts/contact.tcc
  include/contacts/contact_friction.h
  include/contacts/contact_friction.tcc
  include/io/io.h
  include/solvers/mpm.h
  include/solvers/mpm_base.h
  include/solvers/mpm_base.tcc
  include/solvers/mpm_explicit.h
  include/solvers/mpm_explicit.tcc
  include/solvers/mpm_scheme/mpm_scheme.h
  include/solvers/mpm_scheme/mpm_scheme.tcc
  include/solvers/mpm_scheme/mpm_scheme_usf.h
  include/solvers/mpm_scheme/mpm_scheme_usf.tcc
  include/solvers/mpm_scheme/mpm_scheme_usl.h
  include/solvers/mpm_scheme/mpm_scheme_usl.tcc
  src/io/io.cc
  src/mpm.cc
  tests/contact_test.cc
  tests/include/write_mesh_particles.h
  tests/include/write_mesh_particles_unitcell.h
  tests/solvers/mpm_explicit_usf_test.cc
  tests/solvers/mpm_explicit_usf_unitcell_test.cc
  tests/solvers/mpm_explicit_usl_test.cc
  tests/solvers/mpm_explicit_usl_unitcell_test.cc
  tests/solvers/mpm_scheme_test.cc
Labels: Priority: High, Status: Review needed, Type: Refactor

#689 Refactor MPI serialization
  .circleci/config.yml
  CMakeLists.txt
  include/mesh.h
  include/mesh.tcc
  include/mpi_datatypes.h
  include/particles/particle.h
  include/particles/particle.tcc
  include/particles/particle_base.h
  include/solvers/mpm_explicit.tcc
  src/particle.cc
  tests/graph_test.cc
  tests/mpi_particle_test.cc
  tests/mpi_transfer_particle_test.cc
  tests/particle_serialize_deserialize_test.cc
Labels: Priority: High, Status: Completed, Status: Review needed, Type: Core feature, Type: Refactor
