Repository cb-geo/mpm, pull requests merged in 2020-06, with the labels that each got.

#645 :wrench: Fixes #644 use MPI_STATUS_IGNORE when recv status is not used
  include/graph.tcc
  include/mesh.tcc
Labels: Priority: Low, Status: Completed, Type: Enhancement

#647 :bug: :wrench: Fix incorrectparticle length calculation for GIMP
  include/particles/particle.tcc
Labels: Priority: High, Status: Completed, Type: Bug

#648 Feature/contact/compute momenta change
  include/mesh.tcc
  include/node.h
  include/node.tcc
  include/node_base.h
  include/solvers/mpm_explicit.tcc
  tests/interface_test.cc
Labels: Priority: Medium, Status: Completed, Type: Core feature

#653 [Hotfix] fix factor in material utility to be positive
  include/materials/material_utility.tcc
Labels: Priority: Critical, Type: Bug

#649 Feature/contact/compute displacements
  include/mesh.tcc
  include/node.h
  include/node.tcc
  include/node_base.h
  include/particles/particle.h
  include/particles/particle.tcc
  include/particles/particle_base.h
  include/solvers/mpm_explicit.tcc
  tests/interface_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature
