Repository cb-geo/mpm, pull requests merged in 2020-01, with the labels that each got.

#536 Remove quadrature
  include/mpm_base.h
  include/solvers/mpm_explicit.tcc
Labels: Priority: Low

#537 Refactor remove particles when transferring MPI processes
  include/mesh.h
  include/mesh.tcc
  tests/mesh_test.cc
Labels: Priority: High, Status: Completed, Type: Core feature, Type: Refactor

#538 :fire: Remove unused levelset functions
  include/levelset.h
  include/levelset.tcc
Labels: Priority: Low, Status: Completed, Type: Refactor

#533 Damping/cundall
  include/mpm_base.h
  include/mpm_base.tcc
  include/node.h
  include/node.tcc
  include/node_base.h
  include/solvers/mpm_explicit.h
  include/solvers/mpm_explicit.tcc
  tests/io/io_test.cc
  tests/io/write_mesh_particles.cc
  tests/io/write_mesh_particles_unitcell.cc
  tests/node_test.cc
Labels: Priority: Low, Status: In progress, Type: Core feature

#539 Refactor/particle node
  include/cell.h
  include/cell.tcc
  include/mesh.h
  include/mesh.tcc
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/cell_test.cc
  tests/mesh_test.cc
  tests/particle_test.cc
Labels: Priority: High, Status: Completed, Type: Refactor

#540 Performance/remove tbb
  include/particle.tcc
  include/particle_base.h
Labels: Priority: Critical, Status: Completed, Type: Performance

#508 :computer: Mohr Coulomb softening
  CMakeLists.txt
  include/material/mohr_coulomb.h
  include/material/mohr_coulomb.tcc
  src/material.cc
  tests/material/mohr_coulomb_test.cc
Labels: Priority: High, Status: Completed, Status: Review needed, Type: Core feature

#541 :computer: Using sin function for loads
  CMakeLists.txt
  include/functions/function_base.h
  include/functions/linear_function.h
  include/functions/sin_function.h
  src/functions/functions.cc
  src/functions/linear_function.cc
  src/functions/sin_function.cc
  tests/functions/linear_function_test.cc
  tests/functions/sin_function_test.cc
Labels: Priority: Low, Status: Completed, Type: Core feature

#542 :hammer: Fix incorrect check of file in particle stresses
  include/mpm_base.tcc
Labels: Priority: Low, Status: Completed, Type: Bug

#543 :computer: Refactor cell neighbours
  include/mesh.tcc
Labels: Priority: Low, Status: Completed, Type: Performance

#544 VTK statevars
  include/io/vtk_writer.h
  include/mesh.h
  include/mesh.tcc
  include/mpm_base.h
  include/mpm_base.tcc
  include/particle.h
  src/io/vtk_writer.cc
  tests/io/write_mesh_particles.cc
  tests/io/write_mesh_particles_unitcell.cc
  tests/mesh_test.cc
Labels: Priority: Medium, Status: Completed, Type: Viz

#545 :computer: Set state variables to nan if not present
  include/io/vtk_writer.h
  include/particle.h
  tests/particle_test.cc
Labels: Priority: Low, Status: Completed, Type: Bug

#546 :hammer: Handle scalar variales in pvtp wrapper for state variables
  include/io/vtk_writer.h
  src/io/vtk_writer.cc
  tests/io/vtk_writer_test.cc
Labels: Priority: Medium, Status: Completed, Type: Bug

#547 :rocket: Adding noexcept to improve performance
  CMakeLists.txt
  cmake/FindMKL.cmake
  include/data_types.h
  include/node.h
  include/node.tcc
  include/node_base.h
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/mesh_test.cc
  tests/node_test.cc
  tests/particle_test.cc
Labels: Priority: Medium, Status: Completed, Type: Performance

#548 :art: Photo-realistic rendering with Disney partio
  .circleci/config.yml
  CMakeLists.txt
  README.md
  cmake/FindPartio.cmake
  include/io/partio_writer.h
  include/mesh.h
  include/mesh.tcc
  include/mpm.h
  include/mpm_base.h
  include/mpm_base.tcc
  include/solvers/mpm_explicit.tcc
  src/io/partio_writer.cc
  tests/mesh_test.cc
Labels: Priority: Medium, Status: Completed, Type: Viz

#549 :hammer: Fix pdstrain parallel vtp
  .clang-format
  CMakeLists.txt
  clang-tools/format.sh
  include/elements/.clang-format
  include/elements/2d/.clang-format
  include/elements/3d/.clang-format
  include/material/.clang-format
  include/mpm_base.tcc
  src/.clang-format
  src/io/vtk_writer.cc
  tests/.clang-format
  tests/io/vtk_writer_test.cc
Labels: Priority: Low, Status: Completed, Type: Bug

#550 :rocket: Improve node-node halo region MPI communication
  include/mesh.h
  include/mesh.tcc
  include/node.h
  include/node_base.h
  include/solvers/mpm_explicit.tcc
  tests/mesh_test.cc
  tests/node_test.cc
Labels: Priority: High, Status: Completed, Type: Performance

#551 :hammer: Revert improve node-node halo region MPI communication
  include/mesh.h
  include/mesh.tcc
  include/node.h
  include/node_base.h
  include/solvers/mpm_explicit.tcc
  tests/mesh_test.cc
  tests/node_test.cc
Labels: Priority: Critical

#552 Quadrature 4 - (16 for 2D, 64 for 3D)
  include/elements/2d/quadrilateral_quadrature.h
  include/elements/2d/quadrilateral_quadrature.tcc
  include/elements/3d/hexahedron_quadrature.h
  include/elements/3d/hexahedron_quadrature.tcc
  tests/elements/hexahedron_quadrature_test.cc
  tests/elements/quadrilateral_quadrature_test.cc
Labels: Priority: Medium, Status: Review needed, Type: Core feature

#553 :rocket: Allreduce halo
  include/mesh.h
  include/mesh.tcc
Labels: Priority: High, Status: Completed, Type: Performance

#554 :hammer: Add 64 and 16 quadratures for hex and quad to factory
  include/elements/2d/quadrilateral_element.tcc
  include/elements/3d/hexahedron_element.tcc
  src/quadrature.cc
  tests/cell_test.cc
Labels: Priority: Medium, Status: Completed, Type: Bug

#555 Halo exchange for MPI scaling
  CMakeLists.txt
  README.md
  include/data_types.h
  include/mesh.h
  include/mesh.tcc
  include/solvers/mpm_explicit.tcc
  tests/mesh_test.cc
Labels: Priority: High, Status: Completed, Type: Performance

#494 Norsand
  CMakeLists.txt
  include/material/norsand.h
  include/material/norsand.tcc
  include/mesh.tcc
  src/material.cc
  tests/material/norsand_test.cc
Labels: Priority: Medium, Status: Review needed, Type: Core feature

#557 :computer: Nodal forces constraints fixes #556
  include/io/io_mesh.h
  include/io/io_mesh_ascii.h
  include/io/io_mesh_ascii.tcc
  include/mesh.h
  include/mesh.tcc
  include/mpm_base.tcc
  include/node.h
  tests/io/io_mesh_ascii_test.cc
  tests/io/write_mesh_particles.cc
  tests/io/write_mesh_particles_unitcell.cc
  tests/mesh_test.cc
Labels: Priority: Low, Status: Completed, Type: Core feature
