Repository cb-geo/mpm, pull requests merged in 2020-05, with the labels that each got.

#588 Interface nodal properties
  CMakeLists.txt
  include/mesh.h
  include/nodal_properties.h
  include/node.h
  include/node.tcc
  include/node_base.h
  include/particles/particle.h
  include/particles/particle.tcc
  include/particles/particle_base.h
  src/nodal_properties.cc
  tests/interface_test.cc
  tests/nodal_properties_test.cc
Labels: Priority: High, Status: In progress, Type: Core feature

#616 :rocket: Parallel/dynamic load balancing
  .circleci/config.yml
  include/cell.h
  include/graph.h
  include/graph.tcc
  include/io/io.h
  include/mesh.h
  include/mesh.tcc
  include/solvers/mpm.h
  include/solvers/mpm_base.h
  include/solvers/mpm_base.tcc
  include/solvers/mpm_explicit.h
  include/solvers/mpm_explicit.tcc
  tests/cell_test.cc
  tests/graph_test.cc
  tests/mpi_transfer_particle_test.cc
Labels: Priority: Medium, Status: Completed, Type: Performance

#619 :bug: Fixed the bug of state_variables in material models
  include/materials/modified_cam_clay.tcc
  include/materials/mohr_coulomb.tcc
  tests/materials/modified_cam_clay_test.cc
  tests/materials/mohr_coulomb_test.cc
Labels: Priority: Critical, Status: Completed, Type: Core feature

#617 :hammer: Refactor/constraints in Mesh
  CMakeLists.txt
  include/loads_bcs/constraints.h
  include/loads_bcs/constraints.tcc
  include/mesh.h
  include/mesh.tcc
  include/solvers/mpm_base.h
  include/solvers/mpm_base.tcc
  tests/mesh_test_2d.cc
  tests/mesh_test_3d.cc
Labels: Priority: Medium, Status: In progress, Type: Refactor

#622 :wrench: Use default MPI_TAG to avoid mpi_tag overflow fixes #620
  include/mesh.tcc
Labels: Priority: Critical, Status: Completed, Type: Bug

#624 Resume bug
  include/containers/map.h
  include/mesh.h
  include/mesh.tcc
  include/particles/particle.tcc
  include/solvers/mpm_base.tcc
  include/solvers/mpm_explicit.tcc
  tests/node_map_test.cc
Labels: Priority: Critical, Status: Completed, Type: Bug

#627 Fix dynamic loadbalance
  include/cell.h
  include/cell.tcc
  include/graph.h
  include/graph.tcc
  include/mesh.h
  include/mesh.tcc
  include/solvers/mpm.h
  include/solvers/mpm_base.tcc
  include/solvers/mpm_explicit.tcc
  tests/cell_test.cc
  tests/graph_test.cc
  tests/mpi_transfer_particle_test.cc
Labels: Priority: Critical, Status: Completed, Status: In progress, Type: Bug

#629 Nighly builds of benchmarks
  .circleci/config.yml
Labels: Priority: Medium, Status: In progress, Type: Validation

#630 Nightly benchmarks
  .circleci/config.yml
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#631 Static analysis
  include/elements/2d/quadrilateral_element.tcc
  include/graph.tcc
  include/particles/particle.h
  include/particles/particle.tcc
  tests/graph_test.cc
  tests/materials/bingham_test.cc
  tests/materials/mohr_coulomb_test.cc
  tests/materials/newtonian_test.cc
  tests/mesh_test_2d.cc
  tests/mesh_test_3d.cc
  tests/mpi_transfer_particle_test.cc
  tests/particle_test.cc
Labels: Priority: Low, Status: Completed, Type: Enhancement

#632 :pencil: Whitelist files in gitignore
  .gitignore
Labels: Priority: Low, Status: Completed, Type: Enhancement

#618 Create nodal properties pool in mesh
  include/mesh.h
  include/mesh.tcc
  include/solvers/mpm_explicit.tcc
  tests/mesh_test_2d.cc
  tests/mesh_test_3d.cc
Labels: Priority: Medium, Status: In progress, Type: Core feature

#638 :pencil: Add description of design details in RFC and changelog
  .github/ISSUE_TEMPLATE/request_for_comments.md
Labels: Priority: Low, Status: Completed, Type: Documentation

#640 :wrench: Fix acceleration on kinematic velocity constraints fixes #639
  include/node.tcc
Labels: Priority: Critical, Status: Completed, Type: Bug

#642 :wrench: Add include guards to protect against NOKAHIP mpi compilation
  tests/mpi_transfer_particle_test.cc
Labels: Priority: Critical, Status: Completed, Type: Bug
