Repository cb-geo/mpm, pull requests merged in 2020-02, with the labels that each got.

#558 Fix the bug of particles velocity constraints
  include/mpm_base.tcc
Labels: Priority: Critical, Status: Completed, Type: Bug

#560 :hammer: Fixes compilation use due to std namespace ofstream
  README.md
  src/io/vtk_writer.cc
Labels: Priority: Low, Status: Completed, Type: Bug

#561 Norsand: Update bulk modulus to include bond model
  include/material/norsand.h
  include/material/norsand.tcc
  tests/material/norsand_test.cc
Labels: Priority: Critical, Status: Review needed

#563 :scroll: MPM code authors list
  AUTHORS.md
  README.md
  license.md
Labels: Priority: Low, Status: Completed, Type: Documentation

#565 Clone particle material history
  AUTHORS.md
  include/particle.h
  include/particle.tcc
  include/particle_base.h
  tests/particle_test.cc
Labels: Priority: Medium

#573 Particle injection
  include/generators/injection.h
  include/mesh.h
  include/mesh.tcc
  include/solvers/mpm_explicit.tcc
  tests/mesh_test.cc
Labels: Priority: Medium, Status: Completed, Type: Core feature
