Repository cb-geo/mpm, pull requests merged in 2020-04, with the labels that each got.

#590 :pencil: Run vtk test only if VTK is found
  CMakeLists.txt
  README.md
  include/io/vtk_writer.h
  src/io/vtk_writer.cc
  tests/io/vtk_writer_test.cc
Labels: Priority: Low, Status: Completed, Type: Bug

#591 [Constitutives] MC J2 correction
  include/materials/mohr_coulomb.tcc
  tests/materials/mohr_coulomb_test.cc
Labels: Priority: High, Type: Bug

#596 [Materials] NorSand, fix derivatives of Lode Angle
  include/materials/norsand.tcc
  tests/materials/norsand_test.cc
Labels: Priority: High, Status: Review needed, Type: Bug, Type: Core feature

#595 Add range to sine function
  include/functions/sin_function.h
  src/functions/sin_function.cc
  tests/functions/sin_function_test.cc
Labels: Priority: Medium, Status: Review needed, Type: Enhancement

#600 Material utility operations namespace
  CMakeLists.txt
  include/materials/material.h
  include/materials/material_utility.h
  include/materials/material_utility.tcc
  tests/materials/material_utility_test.cc
Labels: Priority: High, Status: Review needed, Type: Core feature, Type: Refactor

#601 NorSand Lode angle cos
  include/materials/norsand.tcc
  tests/materials/norsand_test.cc
Labels: Priority: Critical, Status: Review needed, Type: Core feature

#605 :bug: Fix missing include stdexcept in factory
  include/factory.h
Labels: Priority: Low, Status: Completed, Type: Bug

#603 Refactor NorSand to include material_utility
  include/materials/norsand.h
  include/materials/norsand.tcc
  tests/materials/norsand_test.cc
Labels: Priority: Low, Status: Review needed, Type: Core feature, Type: Refactor

#608 :checkered_flag: GitHub lock
  .github/ISSUE_TEMPLATE/request_for_comments.md
  .github/lock.yml
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: Priority: Low, Status: Completed, Type: Documentation

#606 Add plastic computations to `material_utility`
  include/materials/material_utility.h
  include/materials/material_utility.tcc
  tests/materials/material_utility_test.cc
Labels: Priority: High, Status: Review needed, Type: Core feature, Type: Refactor

#612 :robot: Add stale bot and Request for info
  .github/config.yml
  .github/stale.yml
  README.md
Labels: Priority: Low, Status: Completed, Type: Enhancement

#610 :computer: Use material utility in MC and MCC model
  include/materials/modified_cam_clay.tcc
  include/materials/mohr_coulomb.tcc
  tests/materials/modified_cam_clay_test.cc
  tests/materials/mohr_coulomb_test.cc
  tests/particle_test.cc
Labels: Priority: Medium, Status: In progress, Type: Enhancement

#607 :hammer: Fix HDF5 material statevars
  include/materials/bingham.h
  include/materials/bingham.tcc
  include/materials/linear_elastic.h
  include/materials/material.h
  include/materials/modified_cam_clay.h
  include/materials/modified_cam_clay.tcc
  include/materials/mohr_coulomb.h
  include/materials/mohr_coulomb.tcc
  include/materials/newtonian.h
  include/materials/newtonian.tcc
  include/materials/norsand.h
  include/materials/norsand.tcc
  include/particles/particle.tcc
  tests/materials/bingham_test.cc
  tests/materials/linear_elastic_test.cc
  tests/materials/modified_cam_clay_test.cc
  tests/materials/mohr_coulomb_test.cc
  tests/materials/newtonian_test.cc
  tests/materials/norsand_test.cc
Labels: Priority: Critical, Status: Completed, Type: Bug

#613 NorSand use pdstrain and make some parameters optional
  include/materials/norsand.h
  include/materials/norsand.tcc
  tests/materials/norsand_test.cc
Labels: Priority: High, Status: Review needed, Type: Core feature
